/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author cruzl
 */
public class VentanaCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCliente
     */
    Cliente cliente;

    public VentanaCliente() {
        initComponents();
        jEditorPane1.setContentType("text/html");
        jLabel_RutaImg.setVisible(false);
        this.setLocationRelativeTo(null);

        cliente = new Cliente(jEditorPane1);
        Thread hilo = new Thread(cliente);
        hilo.start();

        //Hacemos que el scroll baje automaticamente con los mensajes
        jScrollPane2.getVerticalScrollBar().addAdjustmentListener(new AdjustmentListener() {
            public void adjustmentValueChanged(AdjustmentEvent e) {
                e.getAdjustable().setValue(e.getAdjustable().getMaximum());
            }
        });

        //jEditorPane1.setText("<h1>Hola</h1>");
//jEditorPane1.setText("<img src=\\src/Recursos/cool.png\\></img>");
    }
//"<img src= //Recursos/cool.png>"+"<br>"

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Usuario = new javax.swing.JTextField();
        jLabel_RutaImg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Mensaje = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cool.png"))); // NOI18N
        jMenuItem2.setToolTipText("Cool");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/love.png"))); // NOI18N
        jMenuItem4.setToolTipText("Love");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/nerd.png"))); // NOI18N
        jMenuItem5.setToolTipText("Nerd");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/serio.png"))); // NOI18N
        jMenuItem6.setToolTipText("Laughed");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem6);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/sonreir2.png"))); // NOI18N
        jMenuItem3.setToolTipText("Happy");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/triste.png"))); // NOI18N
        jMenuItem9.setToolTipText("Sad");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(411, 800));
        setMinimumSize(new java.awt.Dimension(450, 418));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(30, 41, 64));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Usuario:");

        jTextField_Usuario.setBackground(new java.awt.Color(30, 41, 64));
        jTextField_Usuario.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jTextField_Usuario.setForeground(new java.awt.Color(204, 204, 255));
        jTextField_Usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 255)));
        jTextField_Usuario.setOpaque(false);

        jLabel_RutaImg.setEnabled(false);
        jLabel_RutaImg.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Usuario)
                .addGap(18, 18, 18)
                .addComponent(jLabel_RutaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_RutaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        jEditorPane1.setEditable(false);
        jScrollPane2.setViewportView(jEditorPane1);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/sonreir.png"))); // NOI18N
        jLabel2.setToolTipText("Emoticon");
        jLabel2.setComponentPopupMenu(jPopupMenu1);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jTextField_Mensaje.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_Mensaje.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jTextField_Mensaje.setForeground(new java.awt.Color(30, 41, 64));
        jTextField_Mensaje.setText("Escribe Tu Mensaje");
        jTextField_Mensaje.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(30, 41, 64)));
        jTextField_Mensaje.setOpaque(false);
        jTextField_Mensaje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_MensajeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_MensajeFocusLost(evt);
            }
        });
        jTextField_Mensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_MensajeKeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/correo-electronico.png"))); // NOI18N
        jLabel3.setToolTipText("Enviar");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/adjuntar.png"))); // NOI18N
        jLabel4.setToolTipText("Adjuntar archivo");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/caucho.png"))); // NOI18N
        jLabel5.setToolTipText("Limpiar Mensaje");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mensaje)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (jTextField_Usuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Para enviar un mensaje primero escribe tu nombre de usuario");
            jTextField_Usuario.setBackground(Color.red);
        } else {
            if (jTextField_Mensaje.getText().equals("")) {

            } else {
                //Sacamos el nombre y el mensaje de las cajas de texto
                String nombre = jTextField_Usuario.getText();
                if (nombre.trim().length() == 0) {
                    nombre = "Nombre";
                }
                String msg = jTextField_Mensaje.getText();
                if (nombre.trim().length() == 0) {
                    return;
                }
                //Limpiamos el cuadro de texto del mensaje
                jTextField_Mensaje.setText("");
                //Utilizamos la funcion del cliente para enviar el mensaje
                cliente.enviarMsg("<strong>" + nombre + ":</strong> " + msg + "<br>");
                // TODO add your handling code here:

            }
            jTextField_Usuario.setBackground(new Color(30, 41, 64));
        }

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if (jTextField_Mensaje.getText().equals("Escribe Tu Mensaje")) {

        } else {
            jTextField_Mensaje.setText("");
            jTextField_Mensaje.setText("Escribe Tu Mensaje");
            jTextField_Usuario.requestFocus();
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTextField_MensajeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MensajeFocusGained
        if (jTextField_Mensaje.getText().equals("Escribe Tu Mensaje")) {
            jTextField_Mensaje.setText("");
        }
    }//GEN-LAST:event_jTextField_MensajeFocusGained

    private void jTextField_MensajeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MensajeFocusLost
        if (jTextField_Mensaje.getText().equals("")) {
            jTextField_Mensaje.setText("Escribe Tu Mensaje");
        }
    }//GEN-LAST:event_jTextField_MensajeFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
//        String lines = "<img src='file:src/Recursos/love.png'>";
//        String nombre = jTextField_Usuario.getText();
//        cliente.enviarMsg("<strong>" + nombre + ":</strong>" + lines + "<br>");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField_MensajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_MensajeKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextField_Usuario.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Para enviar un mensaje primero escribe tu nombre de usuario");
                jTextField_Usuario.setBackground(Color.red);
            } else {
                if (jTextField_Mensaje.getText().equals("")) {

                } else {
                    //Sacamos el nombre y el mensaje de las cajas de texto
                    String nombre = jTextField_Usuario.getText();
                    if (nombre.trim().length() == 0) {
                        nombre = "Nombre";
                    }
                    String msg = jTextField_Mensaje.getText();
                    if (nombre.trim().length() == 0) {
                        return;
                    }
                    //Limpiamos el cuadro de texto del mensaje
                    jTextField_Mensaje.setText("");
                    //Utilizamos la funcion del cliente para enviar el mensaje
                    cliente.enviarMsg("<strong>" + nombre + ":</strong> " + msg + "<br>");
                    // TODO add your handling code here:

                }
                jTextField_Usuario.setBackground(new Color(30, 41, 64));
            }
        }
    }//GEN-LAST:event_jTextField_MensajeKeyReleased

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        //  System.out.println("evento");
        jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY() - 220);
        jPopupMenu1.setVisible(true);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (jTextField_Usuario.getText().equals("")) {
        } else {
            String lines = "<img src='file:src/Recursos/cool.png'>";
            String nombre = jTextField_Usuario.getText();
            cliente.enviarMsg("<strong>" + nombre + ":</strong>" + lines + "<br>");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (jTextField_Usuario.getText().equals("")) {
        } else {
            String lines = "<img src='file:src/Recursos/love.png'>";
            String nombre = jTextField_Usuario.getText();
            cliente.enviarMsg("<strong>" + nombre + ":</strong>" + lines + "<br>");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (jTextField_Usuario.getText().equals("")) {
        } else {
            String lines = "<img src='file:src/Recursos/nerd.png'>";
            String nombre = jTextField_Usuario.getText();
            cliente.enviarMsg("<strong>" + nombre + ":</strong>" + lines + "<br>");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (jTextField_Usuario.getText().equals("")) {
        } else {
            String lines = "<img src='file:src/Recursos/serio.png'>";
            String nombre = jTextField_Usuario.getText();
            cliente.enviarMsg("<strong>" + nombre + ":</strong>" + lines + "<br>");
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (jTextField_Usuario.getText().equals("")) {
        } else {
            String lines = "<img src='file:src/Recursos/sonreir2.png'>";
            String nombre = jTextField_Usuario.getText();
            cliente.enviarMsg("<strong>" + nombre + ":</strong>" + lines + "<br>");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if (jTextField_Usuario.getText().equals("")) {
        } else {
            String lines = "<img src='file:src/Recursos/triste.png'>";
            String nombre = jTextField_Usuario.getText();
            cliente.enviarMsg("<strong>" + nombre + ":</strong>" + lines + "<br>");
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        /*        javax.swing.JFileChooser ventanaEscojer = new javax.swing.JFileChooser();
                int seleccion = ventanaEscojer.showOpenDialog(ventanaEscojer);
                String path = ventanaEscojer.getSelectedFile().getAbsolutePath();


                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    //JOptionPane.showMessageDialog(null, path);
                    cliente.enviarMsg("Enviando Archivo..."+"<br>");
                    RecibirArchivo recibirArchivo = new RecibirArchivo(path, "localhost", 35557, "localhost");
                    recibirArchivo.start();
                    EnviarArchivo enviarArchivo = new EnviarArchivo("localhost", path);
                    enviarArchivo.start();
                   cliente.enviarMsg("Archivo Enviado Existosamente"+"<br>");
                }*/
        clienteArchivoSocket archivosocket = new clienteArchivoSocket();
        archivosocket.iniCliente();
    }//GEN-LAST:event_jLabel4MouseClicked
//src/FotosUsuarios/ADMIN.PNG

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });*/
        VentanaCliente cliente = new VentanaCliente();
        cliente.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_RutaImg;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_Mensaje;
    private javax.swing.JTextField jTextField_Usuario;
    // End of variables declaration//GEN-END:variables
}
